name: dio_performance
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  dio: ^5.3.2
  http: ^1.1.0
  flutter_isolate: ^2.0.4
  chopper: ^7.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  chopper_generator: ^7.0.4
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
